import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner/Banner';
import Header from '../components/header/Header';

export default function Home() {
  return (
    <div id="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Inika:wght@400;700&display=swap" rel="stylesheet" />
      </Head>
      <Header />

      <main>
        <Banner />
      </main>

      <footer>
      </footer>
    </div>
  )
}
